name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: [bug, Needs Triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: repo 
  attributes:
    label: Link to Repo 
    description: In what Github repository did you find this bug on? 
    placeholder: ex.: https://github.com/neighbour-hoods/sensemaker-lite 
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Acess this link...
      2. Type this...
      3. Click that
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Ubuntu 20.04
        - **Holochain**: v0.1.0
        - **nix**: 2.11.1
    value: |
        - OS:
        - Holochain:
        - nix:
    render: markdown
  validations:
    required: false
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
  validations:
    required: false
- type: dropdown
  id: severity 
  attributes:
    label: How critical do you perceive the bug?
    description: |
      Blocker: all operation is compromised
      Critical: can't use a main feature
      Major: some feature is usable but yields different behavior
      Minor: cosmetical issue 
    options:
      - Blocker 
      - Critical 
      - Major
      - Minor 
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
